/*
 * generated by Xtext 2.25.0
 */
package fr.n7.ui;

import com.google.inject.Injector;
import fr.n7.pdl2.ui.internal.Pdl2Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PDL2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(Pdl2Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		Pdl2Activator activator = Pdl2Activator.getInstance();
		return activator != null ? activator.getInjector(Pdl2Activator.FR_N7_PDL2) : null;
	}

}
