/**
 * generated by Xtext 2.25.0
 */
package fr.n7.pDL1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ressource Needed</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.RessourceNeeded#getWd <em>Wd</em>}</li>
 *   <li>{@link fr.n7.pDL1.RessourceNeeded#getRe <em>Re</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getRessourceNeeded()
 * @model
 * @generated
 */
public interface RessourceNeeded extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Wd</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wd</em>' reference.
   * @see #setWd(WorkDefinition)
   * @see fr.n7.pDL1.PDL1Package#getRessourceNeeded_Wd()
   * @model
   * @generated
   */
  WorkDefinition getWd();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceNeeded#getWd <em>Wd</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wd</em>' reference.
   * @see #getWd()
   * @generated
   */
  void setWd(WorkDefinition value);

  /**
   * Returns the value of the '<em><b>Re</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Re</em>' reference.
   * @see #setRe(Ressource)
   * @see fr.n7.pDL1.PDL1Package#getRessourceNeeded_Re()
   * @model
   * @generated
   */
  Ressource getRe();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceNeeded#getRe <em>Re</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Re</em>' reference.
   * @see #getRe()
   * @generated
   */
  void setRe(Ressource value);

} // RessourceNeeded
