/**
 * generated by Xtext 2.25.0
 */
package fr.n7.pDL1.impl;

import fr.n7.pDL1.PDL1Package;
import fr.n7.pDL1.Ressource;
import fr.n7.pDL1.RessourceNeeded;
import fr.n7.pDL1.WorkDefinition;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ressource Needed</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.impl.RessourceNeededImpl#getWd <em>Wd</em>}</li>
 *   <li>{@link fr.n7.pDL1.impl.RessourceNeededImpl#getRe <em>Re</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RessourceNeededImpl extends ProcessElementImpl implements RessourceNeeded
{
  /**
   * The cached value of the '{@link #getWd() <em>Wd</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWd()
   * @generated
   * @ordered
   */
  protected WorkDefinition wd;

  /**
   * The cached value of the '{@link #getRe() <em>Re</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRe()
   * @generated
   * @ordered
   */
  protected Ressource re;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RessourceNeededImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDL1Package.Literals.RESSOURCE_NEEDED;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WorkDefinition getWd()
  {
    if (wd != null && wd.eIsProxy())
    {
      InternalEObject oldWd = (InternalEObject)wd;
      wd = (WorkDefinition)eResolveProxy(oldWd);
      if (wd != oldWd)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PDL1Package.RESSOURCE_NEEDED__WD, oldWd, wd));
      }
    }
    return wd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WorkDefinition basicGetWd()
  {
    return wd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWd(WorkDefinition newWd)
  {
    WorkDefinition oldWd = wd;
    wd = newWd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.RESSOURCE_NEEDED__WD, oldWd, wd));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Ressource getRe()
  {
    if (re != null && re.eIsProxy())
    {
      InternalEObject oldRe = (InternalEObject)re;
      re = (Ressource)eResolveProxy(oldRe);
      if (re != oldRe)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, PDL1Package.RESSOURCE_NEEDED__RE, oldRe, re));
      }
    }
    return re;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Ressource basicGetRe()
  {
    return re;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRe(Ressource newRe)
  {
    Ressource oldRe = re;
    re = newRe;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL1Package.RESSOURCE_NEEDED__RE, oldRe, re));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PDL1Package.RESSOURCE_NEEDED__WD:
        if (resolve) return getWd();
        return basicGetWd();
      case PDL1Package.RESSOURCE_NEEDED__RE:
        if (resolve) return getRe();
        return basicGetRe();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PDL1Package.RESSOURCE_NEEDED__WD:
        setWd((WorkDefinition)newValue);
        return;
      case PDL1Package.RESSOURCE_NEEDED__RE:
        setRe((Ressource)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PDL1Package.RESSOURCE_NEEDED__WD:
        setWd((WorkDefinition)null);
        return;
      case PDL1Package.RESSOURCE_NEEDED__RE:
        setRe((Ressource)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PDL1Package.RESSOURCE_NEEDED__WD:
        return wd != null;
      case PDL1Package.RESSOURCE_NEEDED__RE:
        return re != null;
    }
    return super.eIsSet(featureID);
  }

} //RessourceNeededImpl
