/**
 * generated by Xtext 2.25.0
 */
package fr.n7.pDL2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ressource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL2.Ressource#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.pDL2.Ressource#getWd <em>Wd</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL2.PDL2Package#getRessource()
 * @model
 * @generated
 */
public interface Ressource extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.pDL2.PDL2Package#getRessource_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.pDL2.Ressource#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Wd</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wd</em>' reference.
   * @see #setWd(WorkDefinition)
   * @see fr.n7.pDL2.PDL2Package#getRessource_Wd()
   * @model
   * @generated
   */
  WorkDefinition getWd();

  /**
   * Sets the value of the '{@link fr.n7.pDL2.Ressource#getWd <em>Wd</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wd</em>' reference.
   * @see #getWd()
   * @generated
   */
  void setWd(WorkDefinition value);

} // Ressource
